version: '3'

services:
  zookeeper-dynamic:
    container_name: zookeeper-dynamic
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka-dynamic:
    container_name: kafka-dynamic
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-dynamic:2181
      KAFKA_LISTENERS:
        "INTERNAL://kafka-dynamic:9090,\
         EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS:
        "INTERNAL://kafka-dynamic:9090,\
         EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
        "INTERNAL:PLAINTEXT,\
         EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_MESSAGE_MAX_BYTES: 2000000
  